### ISSUE TITLE
ServiceRequestException: The request failed. null

### ISSUE THREAD

**Issue by joaquinicolas** [alipov/ews-android-api#10]
ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2010_SP2);
                ExchangeCredentials credentials = new WebCredentials("asdasd", "asddeasd);
                service.setCredentials(credentials);
                try {
                    service.setUrl(new URI("https://isaaa.xxxxx.com"));
                    service.setTraceEnabled(true);
                    Log.v("NCR","enviando...");
                    EmailMessage msg = new EmailMessage(service);
                    msg.setSubject("Hello world!");
                    msg.setBody(MessageBody.getMessageBodyFromText("Sent using the EWS Java Api"));
                    msg.getToRecipients().add("joa@gmail.com");

```
                Log.v("NCR","enviando...");
                msg.send();
                Log.v("NCR","enviado.");
            } catch (Exception e) {
                e.printStackTrace();
                Log.e("NCR",e.getMessage(),e);
            }
```

**Comment by alipov** [comment]
Hi @joaquinicolas 

Could you please post the full stack trace?

**Comment by joaquinicolas** [comment]
05-03 09:15:47.750 5806-5806/com.example.jn185090.webforms2 E/NCR: The request failed. null
                                                                   microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. null
                                                                       at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74)
                                                                       at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
                                                                       at microsoft.exchange.webservices.data.core.ExchangeService.internalCreateItems(ExchangeService.java:598)
                                                                       at microsoft.exchange.webservices.data.core.ExchangeService.createItem(ExchangeService.java:657)
                                                                       at microsoft.exchange.webservices.data.core.service.item.Item.internalCreate(Item.java:245)
                                                                       at microsoft.exchange.webservices.data.core.service.item.EmailMessage.internalSend(EmailMessage.java:147)
                                                                       at microsoft.exchange.webservices.data.core.service.item.EmailMessage.send(EmailMessage.java:258)
                                                                       at com.example.mc185249.webforms.MainActivity.onClick(MainActivity.java:259)
                                                                       at android.view.View.performClick(View.java:4438)
                                                                       at android.view.View$PerformClick.run(View.java:18422)
                                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                    Caused by: android.os.NetworkOnMainThreadException
                                                                       at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1145)
                                                                       at java.net.InetAddress.lookupHostByName(InetAddress.java:385)
                                                                       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
                                                                       at java.net.InetAddress.getAllByName(InetAddress.java:214)
                                                                       at android.org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
                                                                       at android.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
                                                                       at android.org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:338)
                                                                       at android.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
                                                                       at android.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
                                                                       at android.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
                                                                       at android.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
                                                                       at android.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
                                                                       at android.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
                                                                       at android.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
                                                                       at microsoft.exchange.webservices.data.core.request.HttpClientWebRequest.executeRequest(HttpClientWebRequest.java:292)
                                                                       at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.getEwsHttpWebResponse(ServiceRequestBase.java:720)
                                                                       at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:639)
                                                                       at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62)
                                                                       at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158) 
                                                                       at microsoft.exchange.webservices.data.core.ExchangeService.internalCreateItems(ExchangeService.java:598) 
                                                                       at microsoft.exchange.webservices.data.core.ExchangeService.createItem(ExchangeService.java:657) 
                                                                       at microsoft.exchange.webservices.data.core.service.item.Item.internalCreate(Item.java:245) 
                                                                       at microsoft.exchange.webservices.data.core.service.item.EmailMessage.internalSend(EmailMessage.java:147) 
                                                                       at microsoft.exchange.webservices.data.core.service.item.EmailMessage.send(EmailMessage.java:258) 
                                                                       at com.example.mc185249.webforms.MainActivity.onClick(MainActivity.java:259) 
                                                                       at android.view.View.performClick(View.java:4438) 
                                                                       at android.view.View$PerformClick.run(View.java:18422) 
                                                                       at android.os.Handler.handleCallback(Handler.java:733) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by alipov** [comment]
> Caused by: android.os.NetworkOnMainThreadException

You're trying to initiate a network call from main thread. You can't do that.

**Comment by khansaad** [comment]
I'm getting the same error, what to do for that? @alipov

**Comment by alipov** [comment]
@khansaad 
If you're having the same **android.os.NetworkOnMainThreadException** exception, then look [here](https://developer.android.com/reference/android/os/NetworkOnMainThreadException.html). Otherwise, open a separate issue.
