### ISSUE TITLE
Caused by: android.javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.XMLOutputFactoryBase not found

### ISSUE THREAD

**Issue by thejaswi28** [alipov/ews-android-api#15]
Following to the issue below,

https://github.com/alipov/ews-android-api/issues/5

I am getting below exception when I test in Samsung Galaxy S5. Could not find a solution for this yet, can you please help me to solve this?

java.lang.RuntimeException: An error occured while executing doInBackground()
                at android.os.AsyncTask$3.done(AsyncTask.java:300) ~[na:0.0]
                at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355) ~[na:0.0]
                at java.util.concurrent.FutureTask.setException(FutureTask.java:222) ~[na:0.0]
                at java.util.concurrent.FutureTask.run(FutureTask.java:242) ~[na:0.0]
                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) ~[na:0.0]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
                at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
Caused by: android.javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.XMLOutputFactoryBase not found
                at android.javax.xml.stream.FactoryFinder.newInstance(FactoryFinder.java:72) ~[na:0.0]
                at android.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:176) ~[na:0.0]
                at android.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:92) ~[na:0.0]
                at android.javax.xml.stream.XMLOutputFactory.newInstance(XMLOutputFactory.java:98) ~[na:0.0]
                at microsoft.exchange.webservices.data.core.EwsServiceXmlWriter.<init>(EwsServiceXmlWriter.java:101) ~[na:0.0]
                at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpWebRequest(ServiceRequestBase.java:690) ~[na:0.0]
                at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpWebRequest(ServiceRequestBase.java:665) ~[na:0.0]
                at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:635) ~[na:0.0]
                at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62) ~[na:0.0]
                at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158) ~[na:0.0]
                at microsoft.exchange.webservices.data.core.ExchangeService.internalBindToItems(ExchangeService.java:1343) ~[na:0.0]
                at microsoft.exchange.webservices.data.core.ExchangeService.bindToItem(ExchangeService.java:1379) ~[na:0.0]
                at microsoft.exchange.webservices.data.core.ExchangeService.bindToItem(ExchangeService.java:1395) ~[na:0.0]
                at microsoft.exchange.webservices.data.core.service.item.EmailMessage.bind(EmailMessage.java:94) ~[na:0.0]
                at com.bp.mobbox.datamanager.EWSManager.downloadAttachment(EWSManager.java:1223) ~[na:0.0]
                at com.bp.mobbox.datamanager.EWSManager.doInBackground(EWSManager.java:172) ~[na:0.0]
                at android.os.AsyncTask$2.call(AsyncTask.java:288) ~[na:0.0]
                at java.util.concurrent.FutureTask.run(FutureTask.java:237) ~[na:0.0]
                ... 4 common frames omitted

**Comment by thejaswi28** [comment]
Any answer for this?

**Comment by saiajaym** [comment]
thejaswi, were u able to build it?

**Comment by thejaswi28** [comment]
I was not having any issue while building the project.. This happens when I try to do any EWS related operations like fetching attachments, new mails etc.

**Comment by alipov** [comment]
@thejaswi28 
Thanks for reporting this issue.
I have a couple of questions to better understand it:
1. Does it happen on one specific device, or on all devices that you've tested (on which devices it worked / didn't worked)?
2. Do you use ProGuard?
3. Do you use multi-dex?
4. Can you decompile your app and verify that com.bea.xml.stream.XMLOutputFactoryBase class exists?

**Comment by thejaswi28** [comment]
@alipov 

Thanks for the response. 
1. Yes it happens on Samsung Galaxy S5 device. App doesn't crash when tested on Samsung Note 2, 3, 4 and 5. 
2. No, I don't use Proguard.
3. Yes, I am using multi-dex
4. I haven't checked this, I will check and update soon.

Update 4: 

No, this class is not there. So I added stax.jar into the library which contains XMLOutputFactoryBase  class. .

**Comment by alipov** [comment]
@thejaswi28 
Which Android version is installed on your S5 device?

**Comment by thejaswi28** [comment]
@alipov 

Android version is 5.0.in Galaxy S5.

**Comment by thejaswi28** [comment]
@alipov 

Any updates on this issue?

**Comment by alipov** [comment]
I don't have a Galaxy S5 device.. 
I'll check it as soon as I'll find one. In the meantime you can try to debug it by yourself and inform me on your findings.

**Comment by thejaswi28** [comment]
@alipov 
Adding to the issue above and mentioned in other if I add those 3 lines in the other issue you mentioned, I am getting below error

android.javax.xml.stream.FactoryConfigurationError: Provider com.sun.xml.stream.ZephyrWriterFactory not found

**Comment by alipov** [comment]
Fixed in #5.
