### ISSUE TITLE
SSL Handshake Error and Factory Configuration Error

### ISSUE THREAD

**Issue by arunsankar8** [alipov/ews-android-api#28]
I have been using ews-android-api.jar for implementing the microsoft ews.
EWS was working fine without an exceptions.

I had to add the below lines of code to solve the Javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException in the android application.

try {
ProviderInstaller.installIfNeeded(getApplicationContext());
SSLContext sslContext;
sslContext = SSLContext.getInstance("TLSv1.1");
sslContext.init(null, null, null);
sslContext.createSSLEngine();
} catch (GooglePlayServicesRepairableException | GooglePlayServicesNotAvailableException
| NoSuchAlgorithmException | KeyManagementException e) {
e.printStackTrace();
}

After adding the code, the SSL issue was solved and the API were working fine but the ews keeps crashing giving the below log.

Caused by: android.javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.XMLOutputFactoryBase not found
at android.javax.xml.stream.FactoryFinder.newInstance(FactoryFinder.java:72)
at android.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:176)
at android.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:92)
at android.javax.xml.stream.XMLOutputFactory.newInstance(XMLOutputFactory.java:98)
at microsoft.exchange.webservices.data.core.EwsServiceXmlWriter.(EwsServiceXmlWriter.java:101)
at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpWebRequest(ServiceRequestBase.java:692)
at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpPoolingWebRequest(ServiceRequestBase.java:682)
at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:639)
at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62)
at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
at microsoft.exchange.webservices.data.core.ExchangeService.bindToFolder(ExchangeService.java:505)
at microsoft.exchange.webservices.data.core.ExchangeService.bindToFolder(ExchangeService.java:523)
at microsoft.exchange.webservices.data.core.service.folder.CalendarFolder.bind(CalendarFolder.java:60)
at microsoft.exchange.webservices.data.core.service.folder.CalendarFolder.bind(CalendarFolder.java:75)
at com.billinar.bookit.helpers.exchange.ExchangeHelper.login(ExchangeHelper.java:183)

Can you please provide the exact steps to resolve the issue.

**Comment by alipov** [comment]
@arunsankar8 As I've already wrote [here](https://github.com/alipov/ews-android-api/issues/5#issuecomment-619101695):  

> It seems that you're using outdated code: `EwsServiceXmlWriter`'s constructor (EwsServiceXmlWriter.java:101) is invoking `XMLOutputFactory.newInstance` (XMLOutputFactory.java:98), instead of `FixedXMLOutputFactory.newInstance`.  

You should build fresh version of ews-android-api library and integrate it within your app.

**Comment by arunsankar8** [comment]
Hi @alipov,
 I will use the latest code and check. Thanks for your valuable time.

**Comment by arunsankar8** [comment]
Hi @alipov 
Can you please help me with the steps to create the latest android-api.jar file from your repository.

**Comment by alipov** [comment]
@arunsankar8 you can find the instructions [here](https://github.com/alipov/ews-android-api/#building).

**Comment by arunsankar8** [comment]
Hi @alipov , 
sorry for the late message, I did tried the instructions and when I tried to build the jar file by executing the gradlew command  "gradlew copySources ews-android-api:build --stacktrace"
 I faced following error,


FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '13.0.2'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.IllegalArgumentException: Could not determine java version from '13.0.2'.
        at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:63)
        at org.gradle.api.JavaVersion.current(JavaVersion.java:72)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)

**Comment by arunsankar8** [comment]
@alipov Please help me with this issue.

**Comment by arunsankar8** [comment]
Hi @alipov 

Thanks for your guidance, everything works fine.
