### ISSUE TITLE
com.bea.xml.stream.XMLOutputFactoryBase not found

### ISSUE THREAD

**Issue by wwahmed** [alipov/ews-android-api#8]
Hello @alipov : 

Thank you for putting this library wrapper and making it available. I noticed a problem in one of the operations, which I suspect isn't covered by the class name substitutions that are in the build script. I thought of reporting it to you and get your advice on (or allow you to update the library) with appropriate substitutions for this to work. 

**Scneario**: Calling getEvents on exchange subscription

**Stacktrace**:

`android.javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.XMLOutputFactoryBase not found
                                                                         at android.javax.xml.stream.FactoryFinder.newInstance(FactoryFinder.java:72)
                                                                         at android.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:176)
                                                                         at android.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:92)
                                                                         at android.javax.xml.stream.XMLOutputFactory.newInstance(XMLOutputFactory.java:98)
                                                                         at microsoft.exchange.webservices.data.core.EwsServiceXmlWriter.<init>(EwsServiceXmlWriter.java:101)
                                                                         at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpWebRequest(ServiceRequestBase.java:692)
                                                                         at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpPoolingWebRequest(ServiceRequestBase.java:682)
                                                                         at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:639)
                                                                         at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62)
                                                                         at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
                                                                         at microsoft.exchange.webservices.data.core.ExchangeService.getEvents(ExchangeService.java:2006)`

*_Screenshot *_below of the relevant class and line where this exception is thrown from. I am wondering if the XML output factory config strings shown here are correct, or does your 'class substitution' in build scripts need to be adjusted?

![image](https://cloud.githubusercontent.com/assets/7716100/14386991/383670d0-fd75-11e5-995f-36a637646fbc.png)

**Comment by alipov** [comment]
Yeah, I have to look on this issue.
Can you in the meantime use the workaround that I've mentioned in #5 ?

**Comment by wwahmed** [comment]
@alipov Thanks Alex. That did fix the issue. I wouldn't even call it a workaround. Seems a legitimate fix.

**Comment by alipov** [comment]
@wwahmed 
Awesome, thanks for the update :)
I call it workaround since the library should handle it by itself (probably using JAR Services Discovery mechanism).

**Comment by wwahmed** [comment]
@alipov By the way, before coming across your repository, I had already accomplished this with an uglier approach. I used maven, and maven shade plugin, along with OpenJDK implementation for the necessary javax.* classes. Yours seems like a much cleaner approach. If you are open to it, I'd like to know more about how you came across this problem and what you did with it. My email is on my profile if you are open to discussing it , but not publicly. 

Thanks

**Comment by wwahmed** [comment]
@alipov I found another error -- for now adding it to this issue here, but let me know if I should create a separate issue for this



`Caused by: java.lang.Error: javax.xml.datatype.DatatypeConfigurationException: Provider org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl not found
	at android.javax.xml.bind.DatatypeConverterImpl.<clinit>(DatatypeConverterImpl.java:907)
	at android.javax.xml.bind.DatatypeConverter.initConverter(DatatypeConverter.java:155)
	at android.javax.xml.bind.DatatypeConverter.parseTime(DatatypeConverter.java:416)
	at microsoft.exchange.webservices.data.property.complex.TimeChange.tryReadElementFromXml(TimeChange.java:229)
	at microsoft.exchange.webservices.data.property.complex.ComplexProperty.internalLoadFromXml(ComplexProperty.java:260)
	at microsoft.exchange.webservices.data.property.complex.ComplexProperty.loadFromXml(ComplexProperty.java:211)
	at microsoft.exchange.webservices.data.property.complex.ComplexProperty.loadFromXml(ComplexProperty.java:311)
	at microsoft.exchange.webservices.data.property.complex.MeetingTimeZone.tryReadElementFromXml(MeetingTimeZone.java:114)
	at microsoft.exchange.webservices.data.property.complex.ComplexProperty.internalLoadFromXml(ComplexProperty.java:260)
	at microsoft.exchange.webservices.data.property.complex.ComplexProperty.loadFromXml(ComplexProperty.java:211)
	at microsoft.exchange.webservices.data.property.complex.ComplexProperty.loadFromXml(ComplexProperty.java:311)
	at microsoft.exchange.webservices.data.property.definition.MeetingTimeZonePropertyDefinition.loadPropertyValueFromXml(MeetingTimeZonePropertyDefinition.java:65)
	at microsoft.exchange.webservices.data.core.PropertyBag.loadFromXml(PropertyBag.java:510)
	at microsoft.exchange.webservices.data.core.service.ServiceObject.loadFromXml(ServiceObject.java:298)
	at microsoft.exchange.webservices.data.core.EwsServiceXmlReader.readServiceObjectsCollectionFromXml(EwsServiceXmlReader.java:169)
	at microsoft.exchange.webservices.data.core.response.GetItemResponse.readElementsFromXml(GetItemResponse.java:77)
	at microsoft.exchange.webservices.data.core.response.ServiceResponse.loadFromXml(ServiceResponse.java:133)
	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.parseResponse(MultiResponseServiceRequest.java:76)
	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.parseResponse(MultiResponseServiceRequest.java:44)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.readResponse(ServiceRequestBase.java:434)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.readResponse(ServiceRequestBase.java:402)
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:63)
	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
	at microsoft.exchange.webservices.data.core.ExchangeService.internalBindToItems(ExchangeService.java:1343)
	at microsoft.exchange.webservices.data.core.ExchangeService.bindToItem(ExchangeService.java:1379)
	at microsoft.exchange.webservices.data.core.ExchangeService.bindToItem(ExchangeService.java:1395)
	at microsoft.exchange.webservices.data.core.service.item.Appointment.bind(Appointment.java:118)
	at microsoft.exchange.webservices.data.core.service.item.Appointment.bindToRecurringMaster(Appointment.java:205)
	at microsoft.exchange.webservices.data.core.service.item.Appointment.bindToRecurringMaster(Appointment.java:185)`

**Comment by wwahmed** [comment]
@alipov And found one more error, on android L emulator (Nexus 5x emulator). This one tries to lookup the Applet class, which is definitely unnecessary...


'Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/applet/Applet;
                                                                        at com.sun.naming.internal.ResourceManager.getInitialEnvironment(ResourceManager.java:126)
                                                                        at android.javax.naming.InitialContext.init(InitialContext.java:222)
                                                                        at android.javax.naming.InitialContext.<init>(InitialContext.java:202)
                                                                        at android.javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:87)
                                                                        at microsoft.exchange.webservices.data.dns.DnsClient.dnsQuery(DnsClient.java:79)
                                                                        at microsoft.exchange.webservices.data.autodiscover.AutodiscoverDnsClient.findBestMatchingSrvRecord(AutodiscoverDnsClient.java:129)
                                                                        at microsoft.exchange.webservices.data.autodiscover.AutodiscoverDnsClient.findAutodiscoverHostFromSrv(AutodiscoverDnsClient.java:102)
                                                                        at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getRedirectionUrlFromDnsSrvRecord(AutodiscoverService.java:767)
                                                                        at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getSettings(AutodiscoverService.java:1180)
                                                                        at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getUserSettings(AutodiscoverService.java:1044)
                                                                        at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.internalGetSoapUserSettings(AutodiscoverService.java:988)
                                                                        at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getUserSettings(AutodiscoverService.java:1851)
                                                                        at microsoft.exchange.webservices.data.core.ExchangeService.getAutodiscoverUrl(ExchangeService.java:3616)
                                                                        at microsoft.exchange.webservices.data.core.ExchangeService.autodiscoverUrl(ExchangeService.java:3541)'

**Comment by alipov** [comment]
Fixed in #5.
